import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// sql.js's wasm binary is embedded (base64) into the bundle rather than shipped
// as a sibling file: BRAT only fetches main.js/manifest.json/styles.css from a
// release, not extra assets, so a separate sql-wasm.wasm never reaches installs.
const wasmBuffer = fs.readFileSync(
	path.resolve("node_modules/sql.js/dist/sql-wasm.wasm")
);
fs.writeFileSync(
	path.resolve("src/sqlWasmBase64.ts"),
	`// Generated by esbuild.config.mjs — do not edit by hand.\nexport const SQL_WASM_BASE64 = "${wasmBuffer.toString("base64")}";\n`
);

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
